Name:           ros-hydro-pr2
Version:        1.0.5
Release:        0%{?dist}
Summary:        ROS pr2 package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-hydro-audio-common
Requires:       ros-hydro-camera1394
Requires:       ros-hydro-hokuyo-node
Requires:       ros-hydro-joystick-drivers
Requires:       ros-hydro-linux-networking
Requires:       ros-hydro-microstrain-3dmgx2-imu
Requires:       ros-hydro-pr2-base
Requires:       ros-hydro-pr2-ethercat-drivers
Requires:       ros-hydro-pr2-navigation-apps
Requires:       ros-hydro-pr2-power-drivers
Requires:       ros-hydro-pr2-robot
Requires:       ros-hydro-prosilica-camera
Requires:       ros-hydro-sicktoolbox
Requires:       ros-hydro-sicktoolbox-wrapper
Requires:       ros-hydro-wge100-driver
Requires:       ros-hydro-wifi-ddwrt
BuildRequires:  ros-hydro-catkin

%description
A metapackage to aggregate several packages.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Tue Mar 17 2015 Devon Ash <dash@clearpathrobotics.com> - 1.0.5-0
- Autogenerated by Bloom

* Tue Oct 07 2014 Devon Ash <dash@clearpathrobotics.com> - 1.0.3-0
- Autogenerated by Bloom

