Name:           ros-hydro-pr2-base
Version:        1.0.3
Release:        0%{?dist}
Summary:        ROS pr2_base package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-hydro-control-msgs
Requires:       ros-hydro-geometry-experimental
Requires:       ros-hydro-joystick-drivers
Requires:       ros-hydro-mobile
Requires:       ros-hydro-moveit-full
Requires:       ros-hydro-moveit-pr2
Requires:       ros-hydro-perception
Requires:       ros-hydro-perception-pcl
Requires:       ros-hydro-pr2-apps
Requires:       ros-hydro-pr2-calibration
Requires:       ros-hydro-pr2-common
Requires:       ros-hydro-pr2-common-actions
Requires:       ros-hydro-pr2-controllers
Requires:       ros-hydro-pr2-kinematics
Requires:       ros-hydro-pr2-mechanism
Requires:       ros-hydro-pr2-navigation
Requires:       ros-hydro-ros-realtime
Requires:       ros-hydro-sql-database
Requires:       ros-hydro-warehouse-ros
BuildRequires:  ros-hydro-catkin

%description
A metapackage to aggregate several packages.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Tue Oct 07 2014 Devon Ash <dash@clearpathrobotics.com> - 1.0.3-0
- Autogenerated by Bloom

