Name:           ros-indigo-pr2-base
Version:        1.1.2
Release:        0%{?dist}
Summary:        ROS pr2_base package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-indigo-geometry-experimental
Requires:       ros-indigo-joystick-drivers
Requires:       ros-indigo-moveit-pr2
Requires:       ros-indigo-perception
Requires:       ros-indigo-perception-pcl
Requires:       ros-indigo-pr2-apps
Requires:       ros-indigo-pr2-calibration
Requires:       ros-indigo-pr2-common
Requires:       ros-indigo-pr2-common-actions
Requires:       ros-indigo-pr2-controllers
Requires:       ros-indigo-pr2-kinematics
Requires:       ros-indigo-pr2-mechanism
Requires:       ros-indigo-pr2-navigation
Requires:       ros-indigo-ros-realtime
Requires:       ros-indigo-sql-database
Requires:       ros-indigo-warehouse-ros
Requires:       ros-indigo-web-interface
BuildRequires:  ros-indigo-catkin

%description
A metapackage to aggregate several packages.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sun Apr 22 2018 Dave Feil-Seifer <dave@cse.unr.edu> - 1.1.2-0
- Autogenerated by Bloom

